/*
 * IPstackAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.ipstack.api.authentication;

/**
 * A data class for Custom Query Parameter credentials.
 */
public class CustomQueryAuthenticationModel {
    private String accessKey;

    /**
     * A Constructor for CustomQueryAuthenticationModel.
     */
    private CustomQueryAuthenticationModel(String accessKey) {
        this.accessKey = accessKey;
    }

    /**
     * Getter for accessKey.
     * @return accessKey The value of access_key.
     */
    public String getAccessKey() {
        return this.accessKey;
    }

    /**
     * Builds a new {@link CustomQueryAuthenticationModel.Builder} object.
     * Creates the instance with the state of the current auth model.
     * @return a new {@link CustomQueryAuthenticationModel.Builder} object.
     */
    public Builder toBuilder() {
        return new Builder(getAccessKey());
    }

    /**
     * A Builder class for Custom Query Parameter credentials.
     */
    public static class Builder {
        private String accessKey;

        /**
         * The constructor with required auth credentials.
         * @param accessKey The value of AccessKey.
         */
        public Builder(String accessKey) {
            if (accessKey == null) {
                throw new NullPointerException("AccessKey cannot be null.");
            }

            this.accessKey = accessKey;
        }

        /**
         * Setter for accessKey.
         * @param accessKey The value of access_key.
         * @return Builder The current instance of Builder.
         */
        public Builder accessKey(String accessKey) {
            if (accessKey == null) {
                throw new NullPointerException("AccessKey cannot be null.");
            }

            this.accessKey = accessKey;
            return this;
        }

        /**
         * Builds the instance of CustomQueryAuthenticationModel using the provided credentials.
         * @return The instance of CustomQueryAuthenticationModel.
         */
        public CustomQueryAuthenticationModel build() {
            return new CustomQueryAuthenticationModel(accessKey);
        }
    }
}