/*
 * IPstackAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.ipstack.api.authentication;

import com.ipstack.api.CustomQueryAuthenticationCredentials;
import io.apimatic.core.authentication.QueryAuth;
import java.util.HashMap;

public class CustomQueryAuthenticationManager extends QueryAuth implements CustomQueryAuthenticationCredentials {

    /**
     * Private instance of the auth model containing the auth credentials.
     */
    private CustomQueryAuthenticationModel authModel;

    /**
     * Constructor that sets custom query parameters.
     */
    public CustomQueryAuthenticationManager(CustomQueryAuthenticationModel authModel) {

        super(new HashMap<String,String>() {
            private static final long serialVersionUID = 1L;
            {
                put("access_key", authModel.getAccessKey());
            }
        });

        this.authModel = authModel;
    }

    /**
     * String value for accessKey.
     * @return accessKey
     */
    public String getAccessKey() {
        return authModel.getAccessKey();
    }

    /**
     * Checks if provided credentials matched with existing ones.
     * @param accessKey String value for credentials.
     * @return true if credentials matched.
     */
    public boolean equals(String accessKey) {
        return accessKey.equals(getAccessKey());
    }

    /**
     * Converts this CustomQueryAuthenticationManager into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CustomQueryAuthenticationManager [" + "accessKey=" + getAccessKey() + "]";
    }
    /**
    * Returns the error message if the auth credentials are not valid.
    * @return the auth specific error message.
    */
    @Override
    public String getErrorMessage() {
        String errorMessage = super.getErrorMessage();
        if (errorMessage == null) {
            return null;
        }

        return "CustomQueryAuthentication - " + errorMessage;
    }

}
