/*
 * IPstackAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.ipstack.api.exceptions;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.ipstack.api.models.Error1;
import io.apimatic.coreinterfaces.http.Context;

/**
 * This is a model class for ErrorException type.
 */
public class ErrorException extends ApiException {
    private static final long serialVersionUID = 6229605470043211574L;
    private Boolean success;
    private Error1 error;

    /**
     * Initialization constructor.
     * @param   reason  The reason for throwing exception
     * @param   context The context of the API exception
     */
    public ErrorException(String reason, Context context) {
        super(reason, context);
    }


    /**
     * Getter for Success.
     * @return Returns the Boolean
     */
    @JsonGetter("success")
    public Boolean getSuccess() {
        return this.success;
    }

    /**
     * Setter for Success.
     * @param success Value for Boolean
     */
    @JsonSetter("success")
    private void setSuccess(Boolean success) {
        this.success = success;
    }

    /**
     * Getter for Error.
     * @return Returns the Error1
     */
    @JsonGetter("error")
    public Error1 getError() {
        return this.error;
    }

    /**
     * Setter for Error.
     * @param error Value for Error1
     */
    @JsonSetter("error")
    private void setError(Error1 error) {
        this.error = error;
    }

    /**
     * Converts this ErrorException into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ErrorException [" + "statusCode=" + getResponseCode() + ", message=" + getMessage()
                + ", success=" + success + ", error=" + error + "]";
    }
}
