/*
 * IPstackAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.ipstack.api;

/**
 * Interface for defining the behavior of CustomQuery Authentication.
 */
public interface CustomQueryAuthenticationCredentials {

    /**
     * String value for accessKey.
     * @return accessKey
     */
    String getAccessKey();

    /**
     * Checks if provided credentials matched with existing ones.
     * @param accessKey String value for credentials.
     * @return true if credentials matched.
     */
    boolean equals(String accessKey);
}
