/*
 * IPstackAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.ipstack.api;

import com.ipstack.api.authentication.CustomQueryAuthenticationManager;
import com.ipstack.api.authentication.CustomQueryAuthenticationModel;
import com.ipstack.api.controllers.BulkIPLookupController;
import com.ipstack.api.controllers.RequesterIPLookupController;
import com.ipstack.api.controllers.StandardIPLookupController;
import com.ipstack.api.http.client.HttpCallback;
import com.ipstack.api.http.client.HttpClientConfiguration;
import com.ipstack.api.http.client.ReadonlyHttpClientConfiguration;
import io.apimatic.core.GlobalConfiguration;
import io.apimatic.coreinterfaces.authentication.Authentication;
import io.apimatic.coreinterfaces.compatibility.CompatibilityFactory;
import io.apimatic.coreinterfaces.http.HttpClient;
import io.apimatic.okhttpclient.adapter.OkClient;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Consumer;
import java.util.function.Supplier;

/**
 * Gateway class for the library.
 * This class acts as a factory for Controllers.
 * It holds the state of the SDK.
 */
public final class IPstackAPIClient implements Configuration {

    /**
     * Private store for controllers.
     */
    private StandardIPLookupController standardIPLookup;
    private BulkIPLookupController bulkIPLookup;
    private RequesterIPLookupController requesterIPLookup;

    private static final CompatibilityFactory compatibilityFactory = new CompatibilityFactoryImpl();

    private static String userAgent = "APIMATIC 3.0";

    /**
     * Current API environment.
     */
    private final Environment environment;

    /**
     * The HTTP Client instance to use for making HTTP requests.
     */
    private final HttpClient httpClient;

    /**
     * Http Client Configuration instance.
     */
    private final ReadonlyHttpClientConfiguration httpClientConfig;

    /**
     * CustomQueryAuthenticationManager.
     */
    private CustomQueryAuthenticationManager customQueryAuthenticationManager;

    /**
     * The instance of CustomQueryAuthenticationModel.
     */
    private CustomQueryAuthenticationModel customQueryAuthenticationModel;

    /**
     * Map of authentication Managers.
     */
    private Map<String, Authentication> authentications = new HashMap<String, Authentication>();

    /**
     * Callback to be called before and after the HTTP call for an endpoint is made.
     */
    private final HttpCallback httpCallback;

    private IPstackAPIClient(Environment environment, HttpClient httpClient,
            ReadonlyHttpClientConfiguration httpClientConfig,
            CustomQueryAuthenticationModel customQueryAuthenticationModel,
            HttpCallback httpCallback) {
        this.environment = environment;
        this.httpClient = httpClient;
        this.httpClientConfig = httpClientConfig;
        this.httpCallback = httpCallback;

        this.customQueryAuthenticationModel = customQueryAuthenticationModel;

        this.customQueryAuthenticationManager = new CustomQueryAuthenticationManager(
                customQueryAuthenticationModel);
        this.authentications.put("apiKeyAuth", customQueryAuthenticationManager);

        GlobalConfiguration globalConfig = new GlobalConfiguration.Builder()
                .httpClient(httpClient).baseUri(server -> getBaseUri(server))
                .compatibilityFactory(compatibilityFactory)
                .authentication(this.authentications)
                .callback(httpCallback)
                .userAgent(userAgent)
                .build();
        standardIPLookup = new StandardIPLookupController(globalConfig);
        bulkIPLookup = new BulkIPLookupController(globalConfig);
        requesterIPLookup = new RequesterIPLookupController(globalConfig);
    }

    /**
     * Shutdown the underlying HttpClient instance.
     */
    public static void shutdown() {
        OkClient.shutdown();
    }

    /**
     * Get the instance of StandardIPLookupController.
     * @return standardIPLookup
     */
    public StandardIPLookupController getStandardIPLookupController() {
        return standardIPLookup;
    }

    /**
     * Get the instance of BulkIPLookupController.
     * @return bulkIPLookup
     */
    public BulkIPLookupController getBulkIPLookupController() {
        return bulkIPLookup;
    }

    /**
     * Get the instance of RequesterIPLookupController.
     * @return requesterIPLookup
     */
    public RequesterIPLookupController getRequesterIPLookupController() {
        return requesterIPLookup;
    }

    /**
     * Current API environment.
     * @return environment
     */
    public Environment getEnvironment() {
        return environment;
    }

    /**
     * The HTTP Client instance to use for making HTTP requests.
     * @return httpClient
     */
    private HttpClient getHttpClient() {
        return httpClient;
    }

    /**
     * Http Client Configuration instance.
     * @return httpClientConfig
     */
    public ReadonlyHttpClientConfiguration getHttpClientConfig() {
        return httpClientConfig;
    }

    /**
     * The credentials to use with CustomQueryAuthentication.
     * @return customQueryAuthenticationCredentials
     */
    public CustomQueryAuthenticationCredentials getCustomQueryAuthenticationCredentials() {
        return customQueryAuthenticationManager;
    }

    /**
     * The auth credential model for CustomQueryAuthentication.
     * @return the instance of CustomQueryAuthenticationModel
     */
    public CustomQueryAuthenticationModel getCustomQueryAuthenticationModel() {
        return customQueryAuthenticationModel;
    }
    /**
     * The timeout to use for making HTTP requests.
     * @deprecated This method will be removed in a future version. Use
     *             {@link #getHttpClientConfig()} instead.
     *
     * @return timeout
     */
    @Deprecated
    public long timeout() {
        return httpClientConfig.getTimeout();
    }

    /**
     * Get base URI by current environment.
     * @param server Server for which to get the base URI
     * @return Processed base URI
     */
    public String getBaseUri(Server server) {
        return environmentMapper(environment, server);
    }

    /**
     * Get base URI by current environment.
     * @return Processed base URI
     */
    public String getBaseUri() {
        return getBaseUri(Server.ENUM_DEFAULT);
    }


    /**
     * Get base URI by current environment.
     * 
     * @param server string for which to get the base URI
     * @return Processed base URI
     */
    public String getBaseUri(String server) {
        return getBaseUri(Server.fromString(server));
    }


    /**
     * Base URLs by environment and server aliases.
     * @param environment Environment for which to get the base URI
     * @param server Server for which to get the base URI
     * @return base URL
     */
    private static String environmentMapper(Environment environment, Server server) {
        if (environment.equals(Environment.PRODUCTION)) {
            if (server.equals(Server.ENUM_DEFAULT)) {
                return "https://api.ipstack.com";
            }
        }
        return "https://api.ipstack.com";
    }

    /**
     * Converts this IPstackAPIClient into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "IPstackAPIClient [" + "environment=" + environment + ", httpClientConfig="
                + httpClientConfig + ", authentications=" + authentications + "]";
    }

    /**
     * Builds a new {@link IPstackAPIClient.Builder} object.
     * Creates the instance with the state of the current client.
     * @return a new {@link IPstackAPIClient.Builder} object
     */
    public Builder newBuilder() {
        Builder builder = new Builder();
        builder.environment = getEnvironment();
        builder.httpClient = getHttpClient();
        builder.customQueryAuthenticationCredentials(getCustomQueryAuthenticationModel()
                .toBuilder().build());
        builder.httpCallback = httpCallback;
        builder.httpClientConfig(() -> ((HttpClientConfiguration) httpClientConfig).newBuilder());
        return builder;
    }

    /**
     * Class to build instances of {@link IPstackAPIClient}.
     */
    public static class Builder {

        private Environment environment = Environment.PRODUCTION;
        private HttpClient httpClient;
        private CustomQueryAuthenticationModel customQueryAuthenticationModel =
                new CustomQueryAuthenticationModel.Builder("").build();
        private HttpCallback httpCallback = null;
        private HttpClientConfiguration.Builder httpClientConfigBuilder =
                new HttpClientConfiguration.Builder();


        /**
         * Credentials setter for CustomQueryAuthentication.
         * @param accessKey String value for accessKey.
         * @deprecated This builder method is deprecated.
         * Use {@link #customQueryAuthenticationCredentials(CustomQueryAuthenticationModel) customQueryAuthenticationCredentials} instead.
         * @return The current instance of builder.
         */
        @Deprecated
        public Builder customQueryAuthenticationCredentials(String accessKey) {
            customQueryAuthenticationModel = customQueryAuthenticationModel.toBuilder()
                .accessKey(accessKey)
                .build();
            return this;
        }

        /**
         * Credentials setter for CustomQueryAuthenticationCredentials.
         * @param customQueryAuthenticationModel The instance of CustomQueryAuthenticationModel.
         * @return The current instance of builder.
         */
        public Builder customQueryAuthenticationCredentials(
                CustomQueryAuthenticationModel customQueryAuthenticationModel) {
            this.customQueryAuthenticationModel = customQueryAuthenticationModel;
            return this;
        }

        /**
         * Current API environment.
         * @param environment The environment for client.
         * @return Builder
         */
        public Builder environment(Environment environment) {
            this.environment = environment;
            return this;
        }

        /**
         * The timeout to use for making HTTP requests.
         * @deprecated This method will be removed in a future version. Use
         *             {@link #httpClientConfig(Consumer) httpClientConfig} instead.
         * @param timeout must be greater then 0.
         * @return Builder
         */
        @Deprecated
        public Builder timeout(long timeout) {
            this.httpClientConfigBuilder.timeout(timeout);
            return this;
        }

        /**
         * HttpCallback.
         * @param httpCallback Callback to be called before and after the HTTP call.
         * @return Builder
         */
        public Builder httpCallback(HttpCallback httpCallback) {
            this.httpCallback = httpCallback;
            return this;
        }

        /**
         * Setter for the Builder of httpClientConfiguration, takes in an operation to be performed
         * on the builder instance of HTTP client configuration.
         * 
         * @param action Consumer for the builder of httpClientConfiguration.
         * @return Builder
         */
        public Builder httpClientConfig(Consumer<HttpClientConfiguration.Builder> action) {
            action.accept(httpClientConfigBuilder);
            return this;
        }

        /**
         * Private Setter for the Builder of httpClientConfiguration, takes in an operation to be performed
         * on the builder instance of HTTP client configuration.
         * 
         * @param supplier Supplier for the builder of httpClientConfiguration.
         * @return Builder
         */
        private Builder httpClientConfig(Supplier<HttpClientConfiguration.Builder> supplier) {
            httpClientConfigBuilder = supplier.get();
            return this;
        }

        /**
         * Builds a new IPstackAPIClient object using the set fields.
         * @return IPstackAPIClient
         */
        public IPstackAPIClient build() {
            HttpClientConfiguration httpClientConfig = httpClientConfigBuilder.build();
            httpClient = new OkClient(httpClientConfig.getConfiguration(), compatibilityFactory);

            return new IPstackAPIClient(environment, httpClient, httpClientConfig,
                    customQueryAuthenticationModel, httpCallback);
        }
    }
}