/*
 * IPstackAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.ipstack.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Error1 type.
 */
public class Error1 {
    private Integer code;
    private String type;
    private String info;

    /**
     * Default constructor.
     */
    public Error1() {
    }

    /**
     * Initialization constructor.
     * @param  code  Integer value for code.
     * @param  type  String value for type.
     * @param  info  String value for info.
     */
    public Error1(
            Integer code,
            String type,
            String info) {
        this.code = code;
        this.type = type;
        this.info = info;
    }

    /**
     * Getter for Code.
     * @return Returns the Integer
     */
    @JsonGetter("code")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getCode() {
        return code;
    }

    /**
     * Setter for Code.
     * @param code Value for Integer
     */
    @JsonSetter("code")
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * Getter for Type.
     * @return Returns the String
     */
    @JsonGetter("type")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getType() {
        return type;
    }

    /**
     * Setter for Type.
     * @param type Value for String
     */
    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for Info.
     * @return Returns the String
     */
    @JsonGetter("info")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getInfo() {
        return info;
    }

    /**
     * Setter for Info.
     * @param info Value for String
     */
    @JsonSetter("info")
    public void setInfo(String info) {
        this.info = info;
    }

    /**
     * Converts this Error1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Error1 [" + "code=" + code + ", type=" + type + ", info=" + info + "]";
    }

    /**
     * Builds a new {@link Error1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Error1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .code(getCode())
                .type(getType())
                .info(getInfo());
        return builder;
    }

    /**
     * Class to build instances of {@link Error1}.
     */
    public static class Builder {
        private Integer code;
        private String type;
        private String info;



        /**
         * Setter for code.
         * @param  code  Integer value for code.
         * @return Builder
         */
        public Builder code(Integer code) {
            this.code = code;
            return this;
        }

        /**
         * Setter for type.
         * @param  type  String value for type.
         * @return Builder
         */
        public Builder type(String type) {
            this.type = type;
            return this;
        }

        /**
         * Setter for info.
         * @param  info  String value for info.
         * @return Builder
         */
        public Builder info(String info) {
            this.info = info;
            return this;
        }

        /**
         * Builds a new {@link Error1} object using the set fields.
         * @return {@link Error1}
         */
        public Error1 build() {
            return new Error1(code, type, info);
        }
    }
}
