/*
 * IPstackAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.ipstack.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for TimeZone type.
 */
public class TimeZone {
    private String id;
    private String currentTime;
    private Integer gmtOffset;
    private String code;
    private Boolean isDaylightSaving;

    /**
     * Default constructor.
     */
    public TimeZone() {
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  currentTime  String value for currentTime.
     * @param  gmtOffset  Integer value for gmtOffset.
     * @param  code  String value for code.
     * @param  isDaylightSaving  Boolean value for isDaylightSaving.
     */
    public TimeZone(
            String id,
            String currentTime,
            Integer gmtOffset,
            String code,
            Boolean isDaylightSaving) {
        this.id = id;
        this.currentTime = currentTime;
        this.gmtOffset = gmtOffset;
        this.code = code;
        this.isDaylightSaving = isDaylightSaving;
    }

    /**
     * Getter for Id.
     * The timezone ID
     * @return Returns the String
     */
    @JsonGetter("id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * The timezone ID
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for CurrentTime.
     * The current time in the timezone
     * @return Returns the String
     */
    @JsonGetter("current_time")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCurrentTime() {
        return currentTime;
    }

    /**
     * Setter for CurrentTime.
     * The current time in the timezone
     * @param currentTime Value for String
     */
    @JsonSetter("current_time")
    public void setCurrentTime(String currentTime) {
        this.currentTime = currentTime;
    }

    /**
     * Getter for GmtOffset.
     * The GMT offset in seconds
     * @return Returns the Integer
     */
    @JsonGetter("gmt_offset")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getGmtOffset() {
        return gmtOffset;
    }

    /**
     * Setter for GmtOffset.
     * The GMT offset in seconds
     * @param gmtOffset Value for Integer
     */
    @JsonSetter("gmt_offset")
    public void setGmtOffset(Integer gmtOffset) {
        this.gmtOffset = gmtOffset;
    }

    /**
     * Getter for Code.
     * The timezone code
     * @return Returns the String
     */
    @JsonGetter("code")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCode() {
        return code;
    }

    /**
     * Setter for Code.
     * The timezone code
     * @param code Value for String
     */
    @JsonSetter("code")
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * Getter for IsDaylightSaving.
     * Whether daylight saving is active
     * @return Returns the Boolean
     */
    @JsonGetter("is_daylight_saving")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getIsDaylightSaving() {
        return isDaylightSaving;
    }

    /**
     * Setter for IsDaylightSaving.
     * Whether daylight saving is active
     * @param isDaylightSaving Value for Boolean
     */
    @JsonSetter("is_daylight_saving")
    public void setIsDaylightSaving(Boolean isDaylightSaving) {
        this.isDaylightSaving = isDaylightSaving;
    }

    /**
     * Converts this TimeZone into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "TimeZone [" + "id=" + id + ", currentTime=" + currentTime + ", gmtOffset="
                + gmtOffset + ", code=" + code + ", isDaylightSaving=" + isDaylightSaving + "]";
    }

    /**
     * Builds a new {@link TimeZone.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link TimeZone.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .id(getId())
                .currentTime(getCurrentTime())
                .gmtOffset(getGmtOffset())
                .code(getCode())
                .isDaylightSaving(getIsDaylightSaving());
        return builder;
    }

    /**
     * Class to build instances of {@link TimeZone}.
     */
    public static class Builder {
        private String id;
        private String currentTime;
        private Integer gmtOffset;
        private String code;
        private Boolean isDaylightSaving;



        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for currentTime.
         * @param  currentTime  String value for currentTime.
         * @return Builder
         */
        public Builder currentTime(String currentTime) {
            this.currentTime = currentTime;
            return this;
        }

        /**
         * Setter for gmtOffset.
         * @param  gmtOffset  Integer value for gmtOffset.
         * @return Builder
         */
        public Builder gmtOffset(Integer gmtOffset) {
            this.gmtOffset = gmtOffset;
            return this;
        }

        /**
         * Setter for code.
         * @param  code  String value for code.
         * @return Builder
         */
        public Builder code(String code) {
            this.code = code;
            return this;
        }

        /**
         * Setter for isDaylightSaving.
         * @param  isDaylightSaving  Boolean value for isDaylightSaving.
         * @return Builder
         */
        public Builder isDaylightSaving(Boolean isDaylightSaving) {
            this.isDaylightSaving = isDaylightSaving;
            return this;
        }

        /**
         * Builds a new {@link TimeZone} object using the set fields.
         * @return {@link TimeZone}
         */
        public TimeZone build() {
            return new TimeZone(id, currentTime, gmtOffset, code, isDaylightSaving);
        }
    }
}
